name: ramseeker
baseurl: http://hyperlinked.co
description: sponsored by

permalink: /:year/:month/:day/:title/
paginate: 5
highlighter: rouge

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
