name: Jim
description: by Jim Fitzsimmons

permalink: /:year/:month/:day/:title/
paginate: 10
highlighter: rouge
gems: [jekyll-paginate]


 



exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
