name: hyperlinked
baseurl: http://hyperlinked.co
description: over-caffeinated all the time

permalink: /:year/:month/:day/:title/
paginate: 10
highlighter: rouge

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
