name: ramseeker
baseurl: http://ramseeker.com
description: sponsored by

permalink: /:year/:month/:day/:title/
paginate: 10
highlighter: rouge

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
